version: "3.9"

services:
  database:
    image: postgres
    container_name: database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=REP
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: application
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local